# image: gcc has a bad version of lcov
# image: ubuntu needs to update tzdata noninteractively
image: ubuntu

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install build-essential cmake libcmocka-dev
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug ./
    - make
  artifacts:
    paths:
      - tests/jsmn_test_*
      - tests/CMakeFiles/jsmn_test_*/*.gcda
      - tests/CMakeFiles/jsmn_test_*/*.gcno
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

doxygen:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install build-essential cmake doxygen
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug ./
    - make jsmn_doc
  artifacts:
    paths:
      - doxygen/
  only:
    - master

# run tests using the binary built before
test:
  stage: test
  needs: ["build"]
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install libcmocka-dev gcovr lcov
  script:
    - mkdir junit
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_default
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_default_low_memory
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_default_mult_json_fail
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_permissive
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_permissive_low_memory
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_permissive_mult_json_fail
  after_script:
    - mkdir coverage
    - lcov --base-directory . --directory . --capture --output-file coverage/coverage.info
    - genhtml coverage/coverage.info --output-directory coverage
    - mkdir cobertura
    - gcovr -r . --xml-pretty -o cobertura/coverage.xml
  coverage: /regular ^\s+lines\.+:\s(\d+\.\d\%)\s\(.*lines\)$/
  artifacts:
    paths:
      - coverage/
    reports:
      cobertura:
        - cobertura/coverage.xml
      junit:
        - junit/jsmn_test_*.xml

pages:
  stage: deploy
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get -y install rsync
  script:
    - mkdir -p public/coverage/
    - rsync -avP coverage/ public/coverage/
    - mkdir -p public/docs/
    - rsync -avP doxygen/ public/docs/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
