# image: gcc has a bad version of lcov
# image: ubuntu needs to update tzdata noninteractively
image: alpine

stages:
- build
- test
- docs
- deploy

build:
  stage: build
  before_script:
    - apk update
    - apk add build-base cmake
    - apk add cmocka-dev
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug ./
    - make
  artifacts:
    paths:
      - tests/jsmn_test_*
      - tests/CMakeFiles/jsmn_test_*/*.gcda
      - tests/CMakeFiles/jsmn_test_*/*.gcno
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  needs:
    - build
  before_script:
    - apk update
    - apk add cmocka-dev
  script:
    - mkdir junit
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_default
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_default_low_memory
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_permissive
    - CMOCKA_XML_FILE='junit/%g.xml' CMOCKA_MESSAGE_OUTPUT=xml tests/jsmn_test_permissive_low_memory
  artifacts:
    paths:
      - tests/CMakeFiles/jsmn_test_*/*.gcda
      - tests/CMakeFiles/jsmn_test_*/*.gcno
    reports:
      junit:
        - junit/jsmn_test_*.xml

coverage:
  stage: docs
#  coverage: /regular ^\s+lines\.+:\s(\d+\.\d\%)\s\(.*lines\)$/
  needs:
    - test
  before_script:
    - apk update
    - apk add gcovr
#    - apk add gcovr lcov
  script:
#    - mkdir coverage
#    - lcov --base-directory . --directory . --capture --output-file coverage/coverage.info
#    - genhtml coverage/coverage.info --output-directory coverage
    - mkdir cobertura
    - gcovr -r . --xml-pretty -o cobertura/coverage.xml
  artifacts:
#    paths:
#      - coverage/
    reports:
      cobertura:
        - cobertura/coverage.xml

doxygen:
  stage: docs
  before_script:
    - apk update
    - apk add build-base cmake
    - apk add doxygen
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug ./
    - make jsmn_doc
  artifacts:
    paths:
      - doxygen/
  only:
    - master

pages:
  stage: deploy
  needs:
    - coverage
    - doxygen
  before_script:
    - apk update
    - apk add rsync
  script:
#    - mkdir -p public/coverage/
#    - rsync -avP coverage/ public/coverage/
    - mkdir -p public/docs/
    - rsync -avP doxygen/ public/docs/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
