# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: ubuntu

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install build-essential cmake libcmocka-dev
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug ./
    - make
  artifacts:
    paths:
      - tests/jsmn_test_*
      - tests/CMakeFiles/jsmn_test_*/*.gcda
      - tests/CMakeFiles/jsmn_test_*/*.gcno
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  before_script:
    - apt update && apt -y install libcmocka-dev gcovr lcov
  script:
    - tests/jsmn_test_default
    - tests/jsmn_test_default_low_memory
    - tests/jsmn_test_permissive
    - tests/jsmn_test_permissive_low_memory
  artifacts:
    paths:
      - CMakeFiles/jsmn_test_*/*.gcno
  after_script:
    - mkdir coverage
    - lcov --base-directory . --directory . --capture --output-file coverage/coverage.info
    - genhtml coverage/coverage.info --output-directory coverage
    - gcovr -r . --xml -o coverage/cobertura-coverage.xml
  artifacts:
    paths:
      - coverage
    reports:
      cobertura: coverage/cobertura-coverage.xml

# pages:
#   stage: deploy
#   dependencies:
#     - test
#   script:
#     - mv coverage public/
#   artifacts:
#     paths:
#       - public
#     expire_in: 30 days
#   only:
#     - master
